# Generated by Django 3.0.5 on 2020-04-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('advice', models.CharField(max_length=255)),
                ('positive', models.CharField(max_length=255)),
                ('weakness', models.CharField(max_length=255)),
                ('like', models.CharField(max_length=255)),
                ('words', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('talents', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
            ],
        ),
    ]
